# Generated by Django 4.0.1 on 2022-02-20 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joboffer',
            old_name='available',
            new_name='active',
        ),
    ]
